Amanieu/parking_lot

- src/rwlock.rs
These now return options, so return `None` when unsuccessful.
> Minor doc fix

- src/mutex.rs
`try_lock` returns an `Option`, not a `Result`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/amanieu/parking_lot/7)
> Fix doc on Mutex

- README.md
- src/lib.rs
- src/mutex.rs
- src/rwlock.rs
Changes the raw lock and unlock methods to work on all `T: ?Sized`, not just `()`. The locking methods are somewhat useless I suppose but being able to unlock after using `mem::forget` on a Guard is useful.
Also removes `unsafe` on the `RwLock` raw locking methods. They are safe as far as I know (equivalent to `mem::forget(self.read())` and such), and there is no `unsafe` on the equivalent `Mutex` methods, so I don't think they are necessary.
> Make raw lock/unlock methods more versatile on Mutex and RwLock

- core/src/thread_parker/unix.rs
On `x86_64-apple-darwin` parking_lot_core currently fails to compile.
```
error[E0308]: mismatched types
--> core/src/thread_parker/unix.rs:177:18
|
177 |         tv_nsec: now.tv_usec * 1000,
|                  ^^^^^^^^^^^^^^^^^^ expected i64, found i32
```
`libc::timespec.tv_nsec` is of type `libc::c_long` (i64 on x86_64). `libc::timeval.tv_usec` is of type `libc::suseconds_t` (i32 on x86_64). On i686 both types are i32 and the cast is a no-op.
> cast suseconds_t to c_long, fix build on x86_64-apple-darwin

- src/raw_remutex.rs
This is not the root module, so you can't access std like that as a relative path. I'd also be pretty happy if we can have a 0.4.2 for this, as I'd like to publish the next version of my crate to crates.io, but it relies on this working ^^'
> Fix Compile Error on emscripten

- core/src/parking_lot.rs
- src/deadlock.rs
In the worst case the unparked deadlocked thread will panic (which is safe in rust definition). As far as I can see that this panic can't be triggered with safe code though. Even if lock guards are leaked (safe) there's no way of unparking the threads waiting on the leaked guard with safe code. As a compromise `acquire_/release_` are still marked unsafe though.
Plus minor doc improvements.
> Make check_deadlock safe

- Cargo.toml
- src/lib.rs
Fixes for changes from https://github.com/rust-lang/rust/pull/43017. Updated version number as well in hopes of a quick release so that https://github.com/SergioBenitez/Rocket/issues/433 is resolved.
> Update for latest nightly, bump version number.

- src/mutex.rs
- src/rwlock.rs
This makes it easier to port applications using RefCell to locks, since RefCell's Ref and RefMut have a map method.
> Add map methods to lock guards

- src/lib.rs
This PR removes feature gates that have been recently stabilized, see rust-lang/rust#46038 for more information
> Remove unnecessary feature gates

- core/Cargo.toml
- core/src/lib.rs
- core/src/parking_lot.rs
- Fix pulldown migration warnings in parking_lot_core
Lists now require an empty line before them, and a link can no longer be
split on multiple lines.
See rust-lang/rust#44229.
This is required to unblock rust-lang/rust#46278.
- Add an explicit type to silence a future compatibility warning
`requeue_threads` now requires an explicit type because of the `is_null`
method call later in the code.
See rust-lang/rust#46906.
- Bump version to 0.2.9
> Fix future compatibilty warnings and bump version

- src/mutex.rs
- src/remutex.rs
Would be awesome to add `?Sized` on `Mutex`'s `Send` and `Sync` in order to match it to https://doc.rust-lang.org/std/sync/struct.Mutex.html in that regard.
> Add `?Sized` on `Send`- and `Sync`-impl for `Mutex` and `ReentrantMutex`

- core/Cargo.toml
In versions of libc prior to 0.2.27, libc::SYS_futex did
not exist. This is required by parking_lot_core when building
with the nightly feature enabled, like so:
cargo +nightly build --features nightly
This patch bumps the minimum acceptable libc version so that
compiles under this configuration. This prevents parking_lot_core
from breaking builds when included in other projects where the
libc version is older than 0.2.27.
> Bump minimum libc version requirement

- src/condvar.rs
- src/mutex.rs
- src/once.rs
- src/remutex.rs
- src/rwlock.rs
debug formatting now respects standard formatting flags:
`sign_plus`, `sign_minus`, `alternate`, or `sign_aware_zero_pad`
> use std::fmt::DebugStruct to format debug output

- .travis.yml
- benchmark/src/mutex.rs
- benchmark/src/rwlock.rs
There are two commits in this PR. 
The first one makes all benchmark threads wait on a common barrier before they start to reduce result skew from some threads starting earlier than others.
The second one adds support for running multiple benchmark iterations and collecting results across all runs.
> Benchmarks now using barriers and support test iterations

- .travis.yml
- appveyor.yml
- core/src/spinwait.rs
SpinWait used to use custom assembly to access the `pause` instruction; this
only works on nightly. Now that [std::sync::atomic::spin_loop_hint](https://doc.rust-lang.org/std/sync/atomic/fn.spin_loop_hint.html) has been
stabilized, this custom assembly is not necessary (code on stable Rust gets
faster, woohoo!).
@Amanieu
> Using spin_loop_hint since it's now stabilized

- core/Cargo.toml
- core/src/spinwait.rs
Pulling in `parking_lot` to the Rust compiler unfortunately had adverse side
effects on the binary dependencies of rustc -- rust-lang/rust#49438. It turns
out this is due to a number of bugs happening all at once, and currently we're
looking for ways to fix the beta/master branches of rustc to fix this for now
(not necessarily in the best way).
This commit removes the activation of the `synchapi` feature of `winapi` which
prevents `libsynchronization.a` from being linked in (and prevents rustc from
accidentally picking up a dependency on a missing DLL). The `synchapi` feature
was only activated for access to the `Sleep` function, but that function
actually resides in `kernel32.dll`. As a result this commit inlines the
definition of `Sleep` into this crate to avoid needing to depend on an …
> Remove dependency on the `synchapi` winapi feature

- Cargo.toml
- core/Cargo.toml
I was browsing [Crates.rs](https://crates.rs/index), an
alternative UI for crates.io, and expected to find parking_lot in
the "Concurrency" category, but I didn't since it looks like
parking_lot doesn't have any category set.  Add a category to aid
with discoverability.
> Add "concurrency" category to Cargo.toml

- Cargo.toml
Took me a while to figure out why the `const fn` functionality wasn't working...
> Enable lock_api/nightly feature from parking_lot/nightly

- core/src/parking_lot.rs
- src/deadlock.rs
Before this commit, these `[Experimental]` parts of the documentation
were seen as intra-links. Those links could not been resolved, resulting
in a warning on nightly.
It would be awesome, if this can be merged and maybe released as a point release, as `cargo doc` on nightly is quite noisy with many dependencies :)
> Escape [] in docs to avoid warnings on nightly

- CHANGELOG.md
- Cargo.toml
- core/Cargo.toml
- core/src/parking_lot.rs
- src/condvar.rs
This simply returns the values already stored in `UnparkResult`.
Please tell me if you'd prefer not to merge the version bump.
* Add return value to both methods to indicate if or how many threads were woken up (BREAKING)
* Bump version to 0.7.0 and add changelog entry
* Add `UnparkResult::requeued_threads`
Fixes #104
> Condvar: Return bool / usize from notify_one / notify_all

- core/build.rs
- core/src/parking_lot.rs
This reduces the `Bucket` struct size from 112 bytes to 64 bytes when compiled on Rust >= 1.25 that supports `#[repr(align(x))]`
> Replace _padding with proper repr(align(x)) on newer Rust

- core/src/parking_lot.rs
Some casting between `usize` and `*const HashTable` could be avoided by representing it as an `AtomicPtr<HashTable>` instead of `AtomicUsize`. Makes the types fit tighter to what they represent.
Also marked `get_hashtable` as safe, since I could not find any way it could have UB.
> Tighter defined hashtable and less unsafe functions

- core/src/word_lock.rs
I tried to reason a bit about the invariants of the unsafe code in WordLock. I think we can get away with them not being `unsafe` with some minor adjustments. Mostly this PR removes `unsafe` keywords from methods and adds `unsafe` blocks within them. But there is one more difference that I'm hoping should make this safe to call from the outside:
```rust
fn unlock(&self) {
let state = self.state.fetch_and(!LOCKED_BIT, Ordering::Release);
...
}
```
Switching from `fetch_sub` to `fetch_and` is intended to make the method not corrupt `self.state` if called on an already unlocked `WordLock`. Previously multiple calls would continue to decrement the integer by one, locking and unlocking it as well as corrupting the part of it that is used as a pointer. By using the bit and operation this should …
> Safer word lock

- core/src/parking_lot.rs
- core/src/spinwait.rs
- core/src/thread_parker/generic.rs
- core/src/thread_parker/linux.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/windows/mod.rs
- core/src/word_lock.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/condvar.rs
- src/elision.rs
- src/mutex.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
- src/remutex.rs
- src/rwlock.rs
Here are most of the changes I needed to make to the code in order to make it compile and run after copying it into libstd over in https://github.com/rust-lang/rust/pull/56410
> Backport libstd style

- .travis.yml
- appveyor.yml
- core/src/parking_lot.rs
- src/condvar.rs
- src/lib.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
- src/util.rs
Unstable support for checked_add on time types was finally merged (https://github.com/rust-lang/rust/pull/56490) so now we can avoid the possible panic that is `Instant::now() + timeout`.
First commit is unrelated. It's just some other simplification I thought it was nice to make.
> No overflow panic on very long timeouts

- Cargo.toml
- lock_api/Cargo.toml
- src/deadlock.rs
- src/elision.rs
- src/lib.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
The new implementation is inspired by boost's [`upgrade_mutex`](https://github.com/boostorg/thread/blob/fc08c1fe2840baeeee143440fba31ef9e9a813c8/include/boost/thread/v2/shared_mutex.hpp#L432) rwlock implementation.
The main benefit is that it fixes #101: upgradable reads no longer block normal reads. The code has also been refactored and is now much simpler than before.
cc @matklad @nikomatsakis
> [WIP] New RwLock implementation

- core/src/parking_lot.rs
- core/src/thread_parker/generic.rs
- core/src/thread_parker/linux.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/mod.rs
- core/src/thread_parker/windows/waitaddress.rs
- core/src/word_lock.rs
These are only ever called from #[inline(never)] functions, so there shouldn't be too much code duplication from monomorphization.
>  Make functions from parking_lot_core #[inline]

- .travis.yml
- Cargo.toml
- README.md
- appveyor.yml
- core/Cargo.toml
- core/build.rs
- core/src/lib.rs
- core/src/parking_lot.rs
- core/src/spinwait.rs
- core/src/thread_parker/generic.rs
- core/src/thread_parker/linux.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/mod.rs
- core/src/thread_parker/windows/waitaddress.rs
- core/src/word_lock.rs
- lock_api/Cargo.toml
- lock_api/src/lib.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/condvar.rs
- src/deadlock.rs
- src/lib.rs
- src/mutex.rs
- src/once.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
- src/remutex.rs
- src/rwlock.rs
As we discussed on IRC. Let's upgrade all these three crates to Rust 2018 edition and get rid of some legacy conditional compilation etc.
Will greatly aid the work to integrate it into libstd over at #119
> Upgrade to rust2018

- .travis.yml
- core/src/lib.rs
- core/src/thread_parker/sgx.rs
- src/rwlock.rs
Adds a `ThreadParker` implementation that is specific to SGX, so that platform does not need to use the generic fallback spin loop based implementation.
This is in preparation of https://github.com/rust-lang/rust/pull/56410.
Ping @jethrogb who is familiar with the platform. I have read the documentation for `wait` and `send` and I have tried cross compiling this code with `--target x86_64-fortanix-unknown-sgx` to make sure it at least compiles. But I have not tested actually running it since I'm not sure how to do that. Please advise on the implementation if you have any feedback.
It would be good if someone with access to an SGX machine could try to run the benchmark tool in `parking_lot` before and after this PR. So we can get some rough numbers on performance of `parking_lot` compared …
> Add SGX thread parker

- core/Cargo.toml
- core/src/lib.rs
- core/src/thread_parker/wasm.rs
This is in preparation for https://github.com/rust-lang/rust/pull/56410. To not make any platform regress from a good thread parking implementation to a spin lock based one, I add real `ThreadParker` implementations for them to `parking_lot`. Wasm's default locking primitives are really basic. I guess that is because wasm still does not have threads? But with the `target_feature = "atomic"` option it does utilize being able to wait on variables, so I thought we might want to do that here as well.
Ping @alexcrichton. You seem to be the one who implemented most of this atomic wasm thread parking logic in the standard library. So maybe you have some valuable input?
I'm submitting this PR before I have had the chance to even try it out myself. So you can stop me if I'm going in the completely …
> Add wasm thread parker

- benchmark/Cargo.toml
- benchmark/src/args.rs
- benchmark/src/mutex.rs
- benchmark/src/rwlock.rs
I realized that the benchmark crate was still Rust 2015. Caused some small problems when I tried to benchmark on some exotic platforms. No reason to not upgrade it I guess.
> Upgrade benchmark crate to Rust 2018

- .travis.yml
- core/Cargo.toml
- core/src/lib.rs
- core/src/thread_parker/redox.rs
This is in preparation for https://github.com/rust-lang/rust/pull/56410. To not make any platform regress from a good thread parking implementation to a spin lock based one, I add real `ThreadParker` implementations for them to `parking_lot`. It also simply makes `parking_lot` usable as a standalone library on Redox.
Ping @jackpot51. You seem to be the one who implemented most of the futex waiting logic in the standard library. So maybe you have some valuable input? Or you could ping someone who might be able to have a look at/help with this.
I started out with the existing `core/src/thread_parker/linux.rs` futex based implementation and basically just changed a few things to make the calls fit into how Redox expects them.
I have been able to verify that this builds, with cross …
> Add Redox thread parker

- .travis.yml
- core/Cargo.toml
- core/src/lib.rs
- core/src/thread_parker/cloudabi.rs
Adding a proper `ThreadParker` implementation for the CloudABI platform, so it does not fall back on the spin lock based `ThreadParker`. This is to expand where `parking_lot` can be used, but also in preparation for https://github.com/rust-lang/rust/pull/56410.
The code in this PR is heavily inspired by, and basically just a mix of, [the existing pthread parker], the CloudABI [condvar] and [rwlock] implementations.
Ping @EdSchouten. Would you mind looking if this implementation seems sane? If you have the resources at hand, running the test suite would be very valuable as well.
I have only verified that this code compiles. I have not been able to run it yet. I will get some new hardware in a few days, then I might be in a better position to play with this for real.
[the existing pthread …
> Add CloudABI thread parker

- Cargo.toml
- build.rs
- core/Cargo.toml
- core/build.rs
- core/src/lib.rs
- src/once.rs
- src/raw_mutex.rs
- src/util.rs
Automatically detecting Rust >= 1.34 and make good use of the now stable `AtomicU{8,32}` types as well as `Instant::checked_add`.
This has been broken out from #119 since that PR is a bit large and this commit is not really related to the crate being used in libstd. We don't really know when the libstd stuff will be merged anyway, and this could be immediately useful to anyone using `parking_lot` on the latest stable Rust.
I'm just generally against "let's just put this in the already open PR, it'll be fine". I find it usually creates more problems than it solves.
> Add version detection for stabilized atomics and checked_add

- src/condvar.rs
- src/lib.rs
- src/once.rs
I realized that the `const fn` versions of `Once::new` and `Condvar::new` should now work on all stable releases we support. So more const to the people!
Since the next release is going to be a breaking release anyway, I took the liberty of removing `ONCE_INIT` in favor of everyone just using the single constructor. More consistent, and feels more idiomatic.
> Make Once and Condvar constructors const fns

- lock_api/Cargo.toml
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
Since we upgraded to Rust 2018 edition we don't need `extern crate`. I also felt it would be nicer to just import the four types we need into scope rather than a wildcard import.
> Remove extern crate serde and don't wildcard import

- core/src/lib.rs
- core/src/parking_lot.rs
- core/src/word_lock.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/condvar.rs
- src/elision.rs
- src/once.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
- src/rwlock.rs
Apparently rustfmt changed the formatting. Running the latest version now yields this result... I can't say I like the new one better than the old. All of the`if`s that are used as expressions that became one liners are harder to read IMO. But if we want to be able to keep using a formatter at all we must adhere to it, or configure it with `rustfmt.toml` if we want to use it, but not get this result 🤷‍♂
> Run latest rustfmt (1.2.2-nightly)

- core/Cargo.toml
- core/src/parking_lot.rs
Trying to solve #138 
The PRNG implementation is stolen from https://github.com/rust-lang/rust/blob/c28084ac16af4ab594b6860958df140e7c876a13/src/libcore/slice/sort.rs#L486-L493 as pointed out in the issue.
If we are happy with the PRNG algorithm, the only question is the seed. I simply used a pointer readily available when creating the `FairTimeout`. We could potentially also use the nanos offset from the elapsed timeout as a seed. Something like:
```rust
let seed = now.duration_since(self.timeout).as_nanos() as u32;
let nanos = Self::gen_u32_with_seed(seed) % 1_000_000;
```
> Implement own xorshift PRNG to avoid rand dependency

- core/Cargo.toml
- core/src/lib.rs
- core/src/parking_lot.rs
- core/src/thread_parker/cloudabi.rs
- core/src/thread_parker/generic.rs
- core/src/thread_parker/linux.rs
- core/src/thread_parker/mod.rs
- core/src/thread_parker/redox.rs
- core/src/thread_parker/sgx.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/wasm.rs
- core/src/thread_parker/windows/mod.rs
- core/src/word_lock.rs
- src/condvar.rs
- src/once.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
Here I address some of the fairly low hanging fruit from https://github.com/faern/parking_lot/pull/1
1. Simplify `unlock_bucket_pair`. https://github.com/faern/parking_lot/pull/1/files#r283107487
2. Use `impl Trait` instead of a bunch of generics around the park/unpark calls. https://github.com/faern/parking_lot/pull/1/files#diff-f0c71d8c95c3701fb57bafd0a8198201R625
3. Just re-format a comment.
4. Remove all `#[inline(never)]`. https://github.com/faern/parking_lot/pull/1/files#diff-936abe3ecea632b68dddc509e87c7c39R142
4. Create a separate trait for the `ThreadParker` and `UnparkHandle` types. So we have a single place to stick the documentation. And to better ensure all implementers have the exact same API. https://github.com/faern/parking_lot/pull/1/files#r283155912
cc @alexcrichton
> Fix feedback from libstd PR, part 1

- .travis.yml
The review for inclusion into libstd pointed out we need to build (and preferably) run tests on all targets we support. This PR does not reach all the way currently, but it improves the situation by at least testing on macOS.
Also, `travis-cargo` seems rather unmaintained, so I went ahead and re-wrote the Travis CI config according to how I usually do it for new crates. Any feedback and improvements suggestions are very welcome. One thing we could do is putting all the `script` stuff inside some `ci/travis.sh` file in order to maybe slightly reduce duplication and repetition by using bash if statements.
> Update Travis-CI config to test macOS

- src/lib.rs
That way, folks who use both parking_lot and lock_api will need only
one entry in Cargo.toml, one optional feature and won't suffer from
parking_lot / lock_api version mismatch.
> reexport lock_api crate

- core/src/util.rs
- src/util.rs
[`hint::unreachable_unchecked`](https://doc.rust-lang.org/nightly/core/hint/fn.unreachable_unchecked.html) stabilized in 1.27.
> Use hint::unreachable_unchecked instead of Void enum

- .travis.yml
- Cargo.toml
- README.md
The latest rand.  Also avoids some annoying crate duplicates for dev. Should not effect end users.
> Upgrade rand dev dependency to 0.7

- CHANGELOG.md
- Cargo.toml
- README.md
- core/Cargo.toml
- lock_api/Cargo.toml
This includes all necessary version changes and overhauls the CHANGELOG to show more recent releases for all three crates (_parking_lot_, _parking_lot_core_, _lock_api_). Before releasing, the top  `(TBD)` should be replaced with the current date and tags for all crates added.    I also request that you add the following tags to this repo retroactively:
``` bash
git tag core-0.5.0 3259fd72e0d76e9c9a6f31ff41a996648fe9ccfa
git tag lock_api-0.1.5 2653619a613bc12dd6ab486f789d98956b65cdf0
git tag lock_api-0.2.0 3259fd72e0d76e9c9a6f31ff41a996648fe9ccfa
git tag lock_api-0.3.0 ace8280969b6362c3f3753506d90122c358de580
```
Fixes #158
> Staging for parking_lot 0.9.0,  _core 0.6.0 and lock_api 0.3.1 releases

- core/Cargo.toml
`cfg-if 0.1.4` and below don't work correctly on Windows. I get a compile error on `parking_lot_core` due to another crate in the build forcing version `0.1.3`.
> Fix compile errors on Windows due to old cfg_if version

- Cargo.toml
- build.rs
- core/Cargo.toml
- core/build.rs
The `autocfg` crate is a bit more robust in terms of how it parses
rustc's version and also doesn't have a dependency on `semver` which can
be a very weighty dependency if its `serde` feature is activated.
> Switch from `rustc_version` to `autocfg`

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
I felt the code order:
```rust
struct Mutex {...}
impl serde::Traits for Mutex {...}
impl Mutex {...}
```
was strange/not optimal. The first thing I want to read after seeing the struct are the main methods. Constructors and similar. The fact that it implements `serde` feature is more of a niche thing that can come much later. I personally think third party trait impls basically always should come after the main impl block and impls for standard library traits.
Then I also noticed not needed `unsafe` block around `UnsafeCell::into_inner`. These lines of code has not been changed for a very long time. So I guess they were still there since before that method became safe in Rust 1.25.
> Small cleanup, moving code, remove unused unsafe block

- src/condvar.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
My main pet peeve here was the renaming of a trait during import because it collided with an existing type. The main problem here IMO was `impl RawMutexTrait for RawMutex`. Then one has to remember that `RawMutexTrait` corresponds to `lock_api::RawMutex`. This is yet another step to take in the head when reading the code. Just using `lock_api::RawMutex` is not much longer, and it immediately makes it much more clear to the reader that the *local type* `RawMutex` implements the trait *from another crate*. Clears up the relationship with these crates a little bit.
For consistency, and for parts of my argument above, I opted to implement all traits in the same files with full paths to the traits, not just the colliding one.
If/when we drop support for Rust 1.31 and 1.32 we can change the …
> Use full path to lock_api traits in other crates

- core/src/parking_lot.rs
- core/src/thread_parker/mod.rs
- src/raw_mutex.rs
Try to move not unsafe stuff out of large unsafe blocks. And keep only the unsafe call at the end in that block. Documenting the safety contract to think about in said call.
Document what the bits in `RawMutex::state`, and what all combinations of that state, means. Please verify the descriptions are correct, since you know all edge cases much better than me :)
Clippy complained about `#[inline]` on function with no body. The corresponding actual implementations still have `#[inline]`
Clippy complained about two unsafe functions with docs, but without a `# Safety` section. So I took what looked like the safety notes of those functions and formatted them according to the standard.
> Add documentation and limit number of expressions in unsafe block for RawMutex

- src/remutex.rs
`mem::uninitialized` was deprecated in 1.38. Usage is not recommended. Here I start getting rid of it in favor of the preferred `mem::MaybeUninit` type.
This PR does not yet replace all occurances of `mem::unintialized`. I wanted to get some feedback on this before I went ahead with the CloudABI thread parker as well.
> Remove some usage of deprecated mem::uninitialized

- core/src/parking_lot.rs
- core/src/word_lock.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
Running clippy on this project gives a hard clippy `error`, not just a `warning`, about us having constants that have interior mutability. However, the lint description (https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const) clarifies that this exact use case is the exception to the rule, and is legit.
Marking it as such in the source code and commenting on it has the following benefits:
* Clippy does not error out and give up. Making it continue analysis and give further warnings. Important to find other problems and potential code smells.
* Makes any reader that runs clippy aware of this, instead of making them think we have a bug.
It's only the `INIT`s in the traits that can't currently be made into `const fn` constructors. `WordLock` could be changed …
> Mark interior mutable consts as allowed

- src/raw_rwlock.rs
Reducing the amount of expressions inside `unsafe` blocks. And adding `// SAFETY:` documentation to all remaining unsafe blocks.
Found two methods where the unsafety leaked out of methods not marked as unsafe(!). So I made them unsafe and documented what has to be upheld.
Found potential panic in closure that is not allowed to panic. But only in debug builds. What do we do about that?
> Add unsafe safety notes to raw_rwlock.rs

- Cargo.toml
Fixes #181.
(To the extent that a future release, e.g. parking_lot 0.9.1, is made a replacement "minimum".)
> Upgrade _core dep (from parking_lot) to latest 0.6.2

- core/src/parking_lot.rs
There should not be anything `unsafe` about locking `HashTable` buckets. There is no input you can give it, nor state you can cause by calling other public functions in this module that will make the lock bucket functions behave unsafely. Unless I missed some aspect of course.
I first made `get_hashtable` and `create_hashtable` return static safe references instead of raw pointers, so working with the returned HashTable became a bit easier. The returned pointers are going to always point to valid HashTables anyway, so I did not see anything unsafe about it. The tables might become inactive, but they will still be there, and never unsafe to access.
> Make locking buckets a safe operation

- core/build.rs
- core/src/lib.rs
- core/src/maybe_uninit.rs
- core/src/thread_parker/cloudabi.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/windows/keyed_event.rs
Follow up to #173. If we vendor the parts of `MaybeUninit` we need for the places where we use it, then we can get rid of all `mem::uninitialized` and still support Rust older than 1.36.
Because my impression is that there is no way `parking_lot` will make it into `std` while using methods `std` has deprecated and explicitly stated no one should use.
I was not able to make the vendored version `#[repr(transparent)]`.
> Replace deprecated mem::uninitialized()

- .travis.yml
- README.md
- appveyor.yml
- core/Cargo.toml
See https://github.com/servo/rust-smallvec/pull/175 for changelog
> Bump smallvec version to 1.0

- core/src/parking_lot.rs
This library could use more tests, to be more robust. This was one of the things pointed out in the review of the integration into std in https://github.com/rust-lang/rust/pull/56410
`WTF::ParkingLot` has a number of tests we can take inspiration from. And this is somewhat of a port of some of those tests. However, when I ported it 1:1 I found a race condition, so I had to implement the semaphore a bit differently.
I also got away without the tests relying on a working mutex or condvar implementation. Because we can't make the `parking_lot_core` tests depend on the higher level `parking_lot`, nor do we want to depend on locking primitives in std if we aim to become the base for those implementations one day.
> Add initial parking_lot_core tests

- Cargo.toml
- core/Cargo.toml
- src/condvar.rs
- src/mutex.rs
- src/once.rs
- src/remutex.rs
- src/rwlock.rs
I went over the crates with Clippy. Some suggested changes are only stylistic, others more optimization oriented. The commit messages should hopefully explain well enough why each change was made. Otherwise see what clippy says on current master :)
I left some warnings, since the suggested changes were not really objectively better, or possibly larger than what I wanted to do right now.
> Misc clippy fixes

- CHANGELOG.md
- Cargo.toml
- README.md
- core/Cargo.toml
- core/src/lib.rs
- lock_api/Cargo.toml
We must first let #193 be merged. Otherwise this changelog is not even correct.
There were a lot of changes since last release. But the vast majority is reformatting and re-arranging to reduce the number of unsafe expressions. As well as adding safety invariant documentation and a few tests. These are cool improvements, but does not affect the public API. I can add something about it in the changelog if you think it's worth it.
`lock_api` only has formatting changes and a few documentation improvements, so I don't think it needs a breaking version change. But might be worth releasing anyway to get the improved documentation out.
The date in the changelog is simply tomorrow. Since I did not think we would have time to release today, and I did not want to just go with `2019-XX-YY` either. …
> Add changelog entries and bump versions for 0.10.0 release

- README.md
- src/mutex.rs
We juuuust had a release. But when sifting through the docs I stumbled upon a `extern crate parking_lot;`. That felt very ancient. So I removed it.
I also found an example with `use` statements that were not sorted. So very minor, but could fix it while I was at it anyway.
> Remove rust2015 style docs

- core/src/parking_lot.rs
`release_resource` should not panic. Because `with_thread_data` may return a `ThreadData` on the stack, and it's empty.
> fix: not panic in destructor

- src/fair_mutex.rs
- src/lib.rs
- src/raw_fair_mutex.rs
Fixes #76. I don't know if there is interest in having a API for a Mutex that is always fair, but solving it at the type level seems better than requiring a state for each mutex. Fairness sometimes is required, so making type level assurances so another dev can't screw up may solve a bunch of problems, it's probably already being done by people that need it since it's just a thin wrapper. 
This implements a `FairMutex` and it's `RawFairMutex`. This could be done for RwLock too if there is interest.
Idk if the tests are required since it's literally calling something already tested, but I just copied the files and made it compile. I had to remove the Condvar test, since Condvar assumes it's a MutexGuard, and doesn't accept a FairMutexGuard.
> Create API for mutex that is always fair

- lock_api/src/lib.rs
- lock_api/src/mutex.rs
As described in #206:
The example implementation for `try_lock` from the `lock_api` crate was incorrect and has been fixed. Additionally a description of what the `bool` returned from `try_lock` means has been added.
> Fix documentation and example for `try_lock`

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/fair_mutex.rs
- src/lib.rs
- src/mutex.rs
- src/remutex.rs
- src/rwlock.rs
This adds a new constructor `const_new` to lock_api's mutexes, reentrant mutexes and RwLocks that allows creating them in a constant context on stable Rust by manually passing in the underlying raw mutex / rwlock.
Additionally, various helper functions are being added to parking_lot that allow creating mutexes, reentrant mutexes, fair mutexes and RwLocks in constant contexts on stable Rust.
> Implement Support for creating the locking primitives in a const context on stable Rust

- Cargo.toml
- README.md
- src/deadlock.rs
I noticed there's a few things I missed in my previous PR.
1. lazy_static is not necessary anymore. We can just use the new const constructor functions instead.
2. The README still mentions lazy_static.
> Remove the lazy_static dependency

- .travis.yml
- bors.toml
- src/elision.rs
- src/lib.rs
`asm!` will be deprecated soon in preparation for the new `asm!` macro, so switch to using `llvm_asm!` instead.
cc https://github.com/rust-lang/rfcs/pull/2843
> Use llvm_asm! instead of asm!

- Cargo.toml
As of https://github.com/Amanieu/parking_lot/commit/c20495bcc5b3e26cd835ec52aea917b44724d7c3 the additions to lock_api in https://github.com/Amanieu/parking_lot/commit/a9961d4ec400ef54a49183f9063ddf40f2ca23e7 are required to build parking_lot; building with lock_api 0.3.{1,2,3} fails due to missing `_::const_new` functions
> Fix required lock_api version

- README.md
Spotted a small typo in the `README`. The target feature for `wasm32-unknown-unknown` should be `atomics` and not `atomic`.
> Update readme and fix typo

- README.md
Replaces the badges in the README with the new workflow.
> Use GitHub badge

- Cargo.toml
- core/Cargo.toml
- core/src/parking_lot.rs
- core/src/thread_parker/cloudabi.rs
- core/src/thread_parker/generic.rs
- core/src/thread_parker/linux.rs
- core/src/thread_parker/mod.rs
- core/src/thread_parker/redox.rs
- core/src/thread_parker/sgx.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/wasm.rs
- core/src/thread_parker/wasm_atomic.rs
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/mod.rs
- core/src/thread_parker/windows/waitaddress.rs
- src/condvar.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
- src/util.rs
Heya, I was trying out [`governor`](https://github.com/antifuchs/governor) (rate limiter) on WASM, which required `parking_lot` to use a wasm compatible `Instant` type, and I came up with this patch.
The underlying `instant::Instant` type is `std::time::Instant` when compiled without enabling the `"stdweb"` or `"wasm-bindgen"` features.
If you'd like to take it I'll be happy; I'm still trying out different rate-limiting implementations, so am not sure if I'll be using this (but if it's merged, then it's more likely that I will).
> Uses `instant::Instant` in place of `std::time::Instant`.

- lock_api/src/remutex.rs
This is useful for any use case that you'd be using a raw mutex for, where you also want reentrancy.
> Make RawReentrantMutex public

- lock_api/src/remutex.rs
I guess I missed this with the other PR :smiley:
> Make RawReentrantMutex::is_locked public

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
But only if deadlock detection is not enabled.
Fixes #197
> Allow lock guards to be sent to other threads

- core/Cargo.toml
- core/src/thread_parker/cloudabi.rs
Hey folks, 
cloudabi was updated to 0.1. The commit https://github.com/NuxiNL/cloudabi/commit/15f18a92925605b8edd278ed049f2520f1fd56f1 is mainly about updating their bitflags dependency thus this crate should be safe to update too.
> Updating cloudabi to 0.1

- lock_api/src/rwlock.rs
> Remove deprecated and unsound MappedRwLockWriteGuard::downgrade

- lock_api/src/lib.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/raw_fair_mutex.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
Methods like `unlock`, `bump`, `upgrade`, `downgrade` and similar all assume that a certain kind of lock is being held. Since the wrapper mutex and guard types in the `lock_api` crate guarantee that these APIs are always used correctly, these methods are made unsafe to allow implementers to skip checks for these conditions. This allows sound and efficient implementations of these traits.
I hope I did not forget any methods or screw up any comments.
> lock_api: Mark unlock and friends unsafe.

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
> lock_api: Allow unsafely accessing data without a guard

- .github/workflows/rust.yml
- src/condvar.rs
- src/rwlock.rs
Fixes https://github.com/Amanieu/parking_lot/issues/251
With this change, all parking_lot tests pass with Miri with https://github.com/rust-lang/miri/pull/1568 applied, except for the `webkit_queue_test`s which are too slow to complete in reasonable time with Miri. (Lowering the number of messages per producer to 100 or 10 makes them pass too.)
> Fix for two Miri issues with unit tests

- benchmark/Cargo.toml
- benchmark/src/mutex.rs
- benchmark/src/rwlock.rs
Since I saw you had pthreads in the benchmarks I figured it would make sense to add windows slim rwlocks to it too
It seems std uses srwlocks internally, but it might still make sense to add this since
1) std could change in the future
2) It has a fallback for windows xp which looks like it would possibly have some runtime overhead (Even if perfectly predicted the branch could still degrade performance since it would take a spot in the branch predictor right?)
3) I see you also have pthread implementations in the benchmarks despite std using pthreads internally
With regards to point (2), I see non trivial differences between srwlock and std in an uncontended case:
> Add winapi srwlock to benchmarks

- src/raw_rwlock.rs
This fixes the TSAN failures in the testsuite.
Fixes #257
cc @Gankra
> RawRwLock::wait_for_readers needs an Acquire to synchronize with unlock_shared

- lock_api/src/lib.rs
- lock_api/src/mutex.rs
- lock_api/src/rwlock.rs
> Fix bounds on Send and Sync impls for lock guards

- core/Cargo.toml
Smallvec 1.4 regresses performance in Firefox, so while we fix it it'd
be nice to be able to not use the new version. parking_lot is not using
try_reserve so it can live with 1.0.
> core: Use a weaker dependency on smallvec.

- core/src/parking_lot.rs
- core/src/thread_parker/wasm_atomic.rs
This PR removes the `Instant` dummy implementation, which is no longer needed as we are using `instant` now instead of `std`. 
I have also added a polyfill for `Instant::checked_duration_since` because it's not yet implemented for the wasm32. Once it gets implemented we can remove it again.
Lastly, I have updated the `thread_parker` to use the latest wasm32 SIMD intrinsics. For reference, check [this](https://github.com/rust-lang/stdarch/commit/56ee49774172a40883c8c63508d1ec93b3d3c7ea#diff-4cad5669e37a1690249bffa95f51506b35cb27dad65188d63e020784c66fa4c0).
> Remove instant dummy and update to latest wasm32 simd intrinsics

- core/src/thread_parker/unix.rs
Without this, `cargo test` fails on OpenBSD -current. I suspect all the BSDs have the same behaviour in this regard, but I don't have the ability to test FreeBSD or NetBSD I'm afraid.
> OpenBSD returns EINVAL in the same way as DragonFlyBSD.

- core/Cargo.toml
Fixes #274 
There was a vulnerability found in smallvec as described in:
* https://github.com/servo/rust-smallvec/issues/252
* https://github.com/RustSec/advisory-db/pull/552
This patch updates the package version to 1.6 which is deemed safe to
use.
> Update smallvec to 1.6

- lock_api/src/remutex.rs
I'm not sure about the naming; I based it off of Python's RLock._is_owned, but Rust obviously has a pretty different meaning of "owned". Maybe a more explicit/verbose name, like `owned_by_thread`?
> Add [Raw]ReentrantMutex::is_owned

- lock_api/src/lib.rs
This (and a subsequent release of `lock_api`) is needed to make https://github.com/rust-lang/rust/pull/84556 work.
> add new const_fn_trait_bound feature gate

- .github/workflows/rust.yml
- Cargo.toml
- lock_api/Cargo.toml
- lock_api/src/lib.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
Resolves #273.
This adds guards for `Mutex` and `RwLock` that allow it to be used from inside of an `Arc`, without lifetime hurdles.
> Add arc_lock feature, with guards that can be accessed from inside of Arc

- core/build.rs
- core/src/word_lock.rs
I was writing some hand-rolled locks for a tutorial, and did some lightweight fuzzing of the locks under thread-sanitizer to check correctness. I used parking_lot::RawMutex as my "control group" to sanity-check my test suite, but it ended up detecting data races in WordLock.
Taking a look, the Orderings seem a bit too loose — lock_slow used Release in the cmpxchg_weak but needs at least Acquire semantics to acquire the lock (although just using Acquire did not appease TSan), and unlock_slow had a similar problem but reversed (although that code more obviously needs at least Acquire, and so makes sense that it needs AcqRel).
That said, I'm *definitely* not sure these are actually minimal orderings, but I wasn't able to reduce any individual ordering further without upsetting TSan. That …
> Fix Ordering on WordLock (tsan detected)

- Cargo.toml
- core/Cargo.toml
- core/src/lib.rs
- core/src/parking_lot.rs
- core/src/thread_parker/generic.rs
- core/src/thread_parker/linux.rs
- core/src/thread_parker/mod.rs
- core/src/thread_parker/redox.rs
- core/src/thread_parker/sgx.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/wasm.rs
- core/src/thread_parker/wasm_atomic.rs
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/mod.rs
- core/src/thread_parker/windows/waitaddress.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/condvar.rs
- src/raw_mutex.rs
- src/raw_rwlock.rs
- src/util.rs
std::time::Instant panics on this target and the external instant crate
adds undesirable external dependencies to the wasm module.
Fixes #269
> Disable eventual fairness on wasm32-unknown-unknown

- lock_api/src/rwlock.rs
- src/raw_rwlock.rs
- src/rwlock.rs
Closes issue #293.
I also ran into the same issue posed in issue #293. Specifically, it was
for implementing an optimistic hybrid lock as described in [this paper][scalable-latches]
in section 2.3, listing #2. 
[scalable-latches]: https://db.in.tum.de/~giceva/papers/damon_latches.pdf?lang=de
> Add a rwlock method to report if lock is held exclusively

- src/elision.rs
- src/lib.rs
To be honest I'm not the most familiar with inline assembly, but afaict the new version is correct. The assembly output is identical, at least, checking `RawRwLock::bump_shared_slow` (which calls both elision impls) using `cargo asm`.
This should be ready for use when `asm!()` is stabilized, cf (well, your own stabilization report I guess) https://github.com/rust-lang/rust/issues/72016#issuecomment-964186287
> Switch from llvm_asm!() to new asm!() macro

- src/fair_mutex.rs
- src/mutex.rs
The description of fair mutexes contained a bunch of typos, and felt a bit
hard to read in general.
> Improve comments on fair mutexes.

- src/elision.rs
- src/lib.rs
> Fix build on latest nightly

- core/Cargo.toml
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/mod.rs
- core/src/thread_parker/windows/waitaddress.rs
Change from using the unofficial winapi bindings, to using the official windows bindings from Microsoft.
I have also a PR open at winit: https://github.com/rust-windowing/winit/pull/2057
They suggested that parking_lot (dependency of winit) should also be switched over to windows-rs.
For this port I am using the more lightweight and lower level windows-sys (which is closer to winapi).
For me build times are faster with windows-rs 🎉 
Before(winapi 1.19s, total time 2.2s):
After(windows-sys 0.94s, total time 1.7s):
> Adopt windows-rs

- .github/workflows/rust.yml
- README.md
- core/src/spinwait.rs
- core/src/thread_parker/generic.rs
Bumps MSRV to 1.49.0
Fixes #295
> Use core::hint::spin_loop instead of the deprecated spin_loop_hint.

- core/Cargo.toml
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/waitaddress.rs
> Target `windows-sys` version `0.32`

- README.md
I made this section of the readme clearer based on your comment here https://github.com/Amanieu/parking_lot/issues/310#issuecomment-1004309603
I figured the primitives having no effect wasnt worth mentioning because wasm32-unknown-unknown is single threaded anyway.
Happy to reword or change anything I wrote.
> Improve readme wasm32-unknown-unknown nightly section

- .github/workflows/rust.yml
Both #325 and #326's CI failed with a linker error.
This seems to be a bug of incremental compilation and is fixed by disabling incremental compilation.
- https://github.com/Amanieu/parking_lot/runs/5495996459?check_suite_focus=true
- https://github.com/Amanieu/parking_lot/runs/5496070565?check_suite_focus=true
> Disable incremental compilation to fix CI failure

- .github/workflows/rust.yml
- core/Cargo.toml
This updates two outdated dependencies:
- windows-sys 0.32.0 -> 0.33.0
- petgraph 0.5.1 -> 0.6.0
(The first commit is from #327, and needed to fix CI failure)
> Update windows-sys to 0.33, petgraph to 0.6

- lock_api/src/mutex.rs
This pr adds `MutexGuard::leak`.
This is particularly useful for obtaining a static reference to data protected by a static mutex without having to keep the guard around.
> add `MutexGuard::leak`

- src/raw_rwlock.rs
> Fix incorrect memory ordering in RwLock

- src/condvar.rs
Addresses #329.
Let me know what your thoughts are. I'm not sure if `WaitWhileResult` is useful, but I included it anyway since it helps with the tests.
> Add Condvar::wait_while convenience methods

- lock_api/src/mutex.rs
This allows the contained `Arc` to be recovered after unlocking the
mutex.
> Add `ArcMutexGuard::into_arc`

- core/src/parking_lot.rs
...without mentioning the word "async" since for majority of rust developers, it
has an entirely different meaning (so does "safety" but I think this is good
enough).
Safety disclaimer is only added to the unpark methods, as those are the only
ones that one might sanely wish to call from an async context.
Happy to tweak the wording if someone has a better suggestion.
> Document async signal safety of unpark methods

- README.md
`Mutex`, `RwLock` and `CondVar` are const-constructible in `std` since [Rust 1.63](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#const-mutex-rwlock-condvar-initialization). In most platforms `pthread` locks have been replaced with ones that do not allocate.
Maybe it should be noted that points 2-5 are implemented in `std` and 1 is partially implemented?
> Update feature advantages over std

- core/src/thread_parker/generic.rs
- core/src/thread_parker/unix.rs
- core/src/thread_parker/windows/keyed_event.rs
- core/src/thread_parker/windows/waitaddress.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/condvar.rs
- src/elision.rs
This previously incorrectly used `&mut T` instead of `&T`.
Fixes #354
This is a breaking change but will be released in a minor version since it fixes a soundness issue.
> Fix `ReentrantMutexGuard::try_map` signature

- .github/workflows/rust.yml
Versions before 1.54 fail to build on the latest XCode.
> Fix CI on macos

- core/src/thread_parker/linux.rs
In a future release of the `libc` crate, `libc::timespec` will contain private padding fields on 32-bit `*-linux-musl` targets and so the struct will no longer be able to be created using the literal initialization syntax.
Update the use of `libc::timespec` to create a value by calling `std::mem::zeroed()` first and then setting the `tv_sec` and `tv_nsec` fields manually which works with both current versions of `libc` as well as the future version which contains that change.
See also https://github.com/rust-lang/libc/pull/2088
> Update use of `libc::timespec` to prepare for future libc version

- core/src/thread_parker/unix.rs
This PR adds support to parking_lot for watchOS. This can be tested by building on a mac with the following command when the watchOS SDK is installed through Xcode:
```
cargo build -Zbuild-std --target=arm64_32-apple-watchos
```
The support simply mirrors macOS and iOS support.
Note: I've also got a `watchos-0.8` branch with the changes cherry picked onto `backport-core-0.8`, I'm not exactly sure how backports are handled.
> Add support for watchOS.

- lock_api/src/mutex.rs
`#[clippy::has_significant_drop]` tells that a structure should be considered when evaluating some lints. Examples of such behavior are the existent `clippy::significant_drop_in_scrutinee` and the soon-to-be-finished https://github.com/rust-lang/rust-clippy/issues/9399.
> Mark `MutexGuard` with `#[clippy::has_significant_drop]`

- lock_api/Cargo.toml
- lock_api/src/lib.rs
This enables all features to be activated for docs.rs with automated annotations if types or functions are feature-gated.
You can preview this locally by running
```
RUSTDOCFLAGS="--cfg=docsrs" cargo +nightly doc --all-features --open
```
> lock_api: Enable doc_auto_cfg on docs.rs

- core/Cargo.toml
- core/src/thread_parker/windows/bindings.rs
While I don’t think the [3-6 month](https://crates.io/crates/windows-sys/versions) update cadence of the [windows-sys](https://crates.io/crates/windows-sys) crate was a substantial issue, dropping that dependency (#374) is certainly your choice. However, by doing so you gave up some functionality and target support which will prevent `parking_lot_core` from linking in many cases. 
The [windows](https://crates.io/crates/windows) and [windows-sys](https://crates.io/crates/windows-sys) crates depend on the [windows-targets](https://crates.io/crates/windows-targets) crate for linker support. The `windows-targets` crate includes only import libs, supports semantic versioning of libs, and optional support for [raw-dylib](https://github.com/rust-lang/rust/issues/58713). It provides explicit …
> Fix linker issues and target support

- lock_api/Cargo.toml
- lock_api/src/lib.rs
Adds a default "atomic_usize" feature as a feature gate for library components that rely on `AtomicUsize`. Some platforms, such as AVR, do not support atomics with large widths.
Current library users will experience no changes, but users on constrained platforms can opt-out by using `default_features = false`.
> lock_api: Add default "atomic_usize" feature

- core/Cargo.toml
- core/src/parking_lot.rs
This adds deadlock_detector support for the WASM target.
Instead of `thread_id` I added a conditional `worker_name` field
> feat(wasm-bindgen): deadlock detector support

- core/Cargo.toml
- core/src/parking_lot.rs
This reverts https://github.com/Amanieu/parking_lot/pull/379 for two reasons:
- This doesn't actually work, because `cfg(target = "...")` is an unstable feature ([RFC](https://rust-lang.github.io/rfcs/3239-cfg-target.html)) and was not enabled.
- Using the worker name as a thread ID is quite unreliable, as they are simply an empty string if not set during their creation, which is commonly not done. Certainly there is nothing in place to make them unique.
In the meantime, `thread-id` now supports `wasm32-unknown-unknown` (https://github.com/ruuda/thread-id/pull/12) in v4.1, so `parking_lot_core` now inherited that support without any changes required.
> Revert #379

- README.md
Currently the documentation on how to target `wasm32-unknown-unknown` with `-C target-feature=+atomics` is incorrect and will yield compile errors.
This is because `wasm32-unknown-unknown` doesn't support unwinding, but `-Zbuild-std` doesn't support automatic selection of the correct panic strategy, so this has to be set manually with `-Zbuild-std=panic_abort,std`.
This PR corrects the documentation to reflect this.
See https://github.com/rust-lang/wg-cargo-std-aware/issues/29.
Fixes #267.
> Adjust the `wasm32-unknown-unknown` atomic docs

- lock_api/src/rwlock.rs
`RwLockUpgradableReadGuard::upgrade` takes the guard by value, so there is currently no way to turn an `&mut` to an upgradable guard into an `&mut` to the underlying data.
This PR remedies that with a closure-based API. `RwLockUpgradableReadGuard::with_upgraded()` takes a mutable reference to an upgradable guard, and:
1) Upgrades the lock
2) Retrieves an `&mut` to the underlying data
3) Passes the `&mut` to a user-provided closure
4) Downgrades the lock back to an upgradable read
5) Returns the result of the closure.
> Add `with_upgraded` API to upgradable read locks

- lock_api/src/remutex.rs
- src/remutex.rs
Closes https://github.com/Amanieu/parking_lot/issues/389
Hopefully the test seems reasonable. I ended up using a channel to try and avoid the `bump()` running before before the thread tries to acquire the lock.
> Fix `ReentrantMutex::bump()` lock count

- Cargo.toml
- core/Cargo.toml
- lock_api/Cargo.toml
This option generates links in source code pages, allowing to jump to definition and to jump back to doc. It makes browsing the source code pages much nicer. You can see it in action [here](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_middle/lib.rs.html#90).
> Add `--generate-link-to-definition` option when building on docs.rs

- core/src/thread_parker/windows/mod.rs
These imports were introduced in 2fb27d35 and were unused at the time and remain so.
> windows: impl `ThreadParkerT` / `UnparkHandleT`.

- .github/workflows/rust.yml
This fixes some warnings about using old versions of node in the GitHub Actions UI:
The following actions uses node12 which is deprecated and
will be forced to run on node16: actions/checkout@v2.
For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> ci: Update `actions/checkout` from v2 to v3.

- core/src/parking_lot.rs
This test is causing failures in Android CI because it is too slow. I suggest reducing the number of repeats.
From our CI:
```
stdout: 
running 12 tests
test parking_lot::tests::unpark_one_one ... ok <0.499s>
test parking_lot::tests::hundred_unpark_all_one ... ok <0.568s>
test parking_lot::tests::unpark_one_fifty ... ok <0.706s>
test parking_lot::tests::unpark_one_fifty_then_fifty_all ... ok <1.489s>
test parking_lot::tests::unpark_one_hundred_fast ... ok <3.500s>
test parking_lot::tests::unpark_all_one ... ok <6.221s>
test parking_lot::tests::unpark_one_fifty_then_fifty_all_fast ... ok <10.103s>
test parking_lot::tests::unpark_all_hundred_fast ... ok <15.896s>
test parking_lot::tests::unpark_all_hundred ... ok <15.980s>
test parking_lot::tests::hundred_unpark_all_one_fast ... ok …
```
> Reduce repeats in unpark_all_one_fast test

- core/src/thread_parker/unix.rs
This PR allows using parking_lot lib to target [tier 3 *-apple builds](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-tvos.html):
Apple tvOS on aarch64
Apple tvOS Simulator on x86_64
> Add apple tvos support

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
This PR changes the visibility of the functions that produce the lock guards to public. 
The inspiration for this comes from my desire to extend the mutex with new locking functions (async locking for example).
I was initially concerned that exposing this might be a bad idea even if it is useful. However, I decided that exposing these functions was no worse than the already public `force_unlock` functions.
> Allow unsafe creation of new lock guards

- Cargo.toml
Add a `rust_version` entry to `Cargo.toml` in order to codify the MSRV for `cargo` to pick it up.  
This leads to a more helpful and more actionable error message, for example:
> error: package `parking_lot v0.12.1 ([…])` cannot be built because
> it requires rustc 1.59 or newer, while the currently active rustc
> version is 1.58.1
Supersedes #347.
> Add MSRV to Cargo.toml

- src/elision.rs
Each function which uses `asm!` is already importing `core::arch::asm` on its own.
> hardware-lock-elision: Remove redundant import.

- core/src/parking_lot.rs
- core/src/thread_parker/mod.rs
- core/src/thread_parker/windows/bindings.rs
- core/src/word_lock.rs
- lock_api/src/lib.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/raw_rwlock.rs
- src/remutex.rs
This fixes missing backticks, imbalanced backticks, old HTML intradoc links, and adds a couple of links.
> Markdown fixes / improvements.

- Cargo.toml
This will enable some features (`arc_lock`, `serde`, and `deadlock_detection`) on the playground (https://play.rust-lang.org). Feature list was copied from `package.metadata.docs.rs`, feel free to change if it isn't right.
See https://github.com/rust-lang/rust-playground/issues/192 for more info.
Many other popular crates have done a similar thing ([serde](https://github.com/serde-rs/serde/blob/44613c7d0190dbb5ecd2d5ec19c636f45b7488cc/serde/Cargo.toml#L26-L27), [tokio](https://github.com/tokio-rs/tokio/blob/7a30504fd423aa782239ead92f3afa3474f8037c/tokio/Cargo.toml#L165-L166), etc).
> Enable some features for the playground

- lock_api/src/rwlock.rs
> Make impl Debug for Rwlock simpler

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
Addresses https://github.com/Amanieu/parking_lot/issues/400 by implementing https://github.com/Amanieu/parking_lot/issues/400#issuecomment-1888695827.
This PR adds `from_raw` methods for `lock_api::{Mutex, ReentrantMutex, RwLock}`. These have the same behavior as the existing legacy `const_new` methods.
These methods are useful with `RawMutex`, etc. implementations which don't support `const` initialization.
> Add `lock_api::{Mutex, ReentrantMutex, RwLock}::from_raw` methods

- lock_api/src/rwlock.rs
- src/rwlock.rs
> Fix panic when calling `with_upgraded` twice on a `ArcRwLockUpgradableReadGuard`

- core/src/lib.rs
Should fix #434 
I don't know the context of the change so I might be missing something important. I only know that I tested on nightly and it works.
> stdarch_wasm_atomic_wait instead of stdsimd

- src/lib.rs
While switching from [`write`](https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html#method.write) to [`write_arc`](https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html#method.write_arc) in some wrapper I'm making, I expected the return to change from `parking_lot::RwLockWriteGuard` to `parking_lot::ArcRwLockWriteGuard`, so:
```rust
pub fn write(&self) -> parking_lot::RwLockWriteGuard<'_, WorldState> { }
// to 
pub fn write_arc(&self) -> parking_lot::ArcRwLockWriteGuard<parking_lot::RawRwLock, WorldState> { }
```
But the `ArcRwLockWriteGuard` isn't present in the root of the crate, even with the `arc_lock` feature;
```
141 |     pub fn write_arc(&self) -> parking_lot::ArcRwLockWriteGuard<parking_lot::RawRwLock, WorldState>  {
| …
```
> Export types provided by arc_lock feature.

- core/src/thread_parker/windows/mod.rs
If I understand correctly, the `failure` ordering of Acquire is required to synchronize with the race-winner's Release and thereby allow use of the returned pointer - like how `Backend::get` itself uses Acquire ordering.
> Use Release/Acquire ordering in thread_parker::windows::Backend::create

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- core/Cargo.toml
- lock_api/Cargo.toml
This avoids breakages when our dev-dependencies drop support for older Rust versions.
> Check MSRV using cargo-msrv in CI

- src/raw_rwlock.rs
The docs for `RawRwLockFair::bump_shared` state (and similarly for `bump_upgradable`):
> This method is functionally equivalent to calling `unlock_shared_fair` followed by `lock_shared`, however it can be much more efficient in the case where there are no waiting threads.
If there is more than one reader and a pending writer currently `bump` is a no-op, but it should release the lock and block trying to re-acquire it.
> Fix RawRwLock::bump_*() not releasing lock when there are multiple readers

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
- src/lib.rs
In addition I also minimized the amount of unsafe code a bit by re-writing `unlock_fair` as simply `drop(T::into_arc_fair(s))`.
> Add missing into_arc(_fair) methods

- lock_api/Cargo.toml
- lock_api/build.rs
- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
This drops the build script and the dependency on `autocfg` for `lock_api`, which isn't needed anymore given that the MSRV is higher than the version the build script was adding special handling for.
> lock_api: drop build script and `autocfg` dependency

- lock_api/src/mutex.rs
- lock_api/src/remutex.rs
- lock_api/src/rwlock.rs
This PR marks some of the `lock` functions in `lock_api` with `#[track_caller]` where they might reasonably panic for fallible locks.
I would like to write a `RawMutex` implementation that behaves like a mutable-borrow-only `RefCell`. This is fairly trivial, but the main difference is that `RefCell` leverages `#[track_caller]` and `std::panic::Location::caller` to provide great panic messages when `debug_assertions` are enabled, indicating where the prior borrow occurred when panicking. I'd like to replicate that, but the issue is that `lock_api::Mutex`'s `lock` function doesn't have the `#[track_caller]` attribute which results in error messages saying "could not borrow when previously borrows here: [in the lock_api::Mutex::lock function]".
In general, if a RawMutex's `lock` …
> Add `#[track_caller]` for better panic messages for fallible locks using `lock_api`.

- benchmark/Cargo.toml
- benchmark/src/args.rs
- benchmark/src/bin/mutex.rs
- benchmark/src/bin/rwlock.rs
- benchmark/src/lib.rs
- benchmark/src/rwlock.rs
I'm trying to resolve  #398 as I strongly agree with [this comment](https://github.com/Amanieu/parking_lot/issues/398#issuecomment-2349247853).
In the process of coming up with benchmark numbers I noticed a few shortcomings of the benchmark crate, notably:
- [The `PthreadRwLock` implementation was calling the wrong function for acquiring the read lock](https://github.com/Amanieu/parking_lot/commit/b1adaefb273d0c8a2e144abf67c05708777dda88)
- [The lack of `RwLock` from stdlib for comparison](https://github.com/Amanieu/parking_lot/commit/79e4a90626a1682b039f3b65490d2f1f8b854160)
The rest of changes are some minor polishments and linting fixes.
---
I'm also planning to add an opinionated benchmark suite runner for making the benchmark numbers more accessible, reproducible, and provable. 
I …
> Benchmark improvments

- Cargo.toml
- README.md
- core/Cargo.toml
- core/src/thread_parker/windows/bindings.rs
- lock_api/Cargo.toml
Supersedes #458
This raises the MSRV to 1.71, and removes the statement that changing the MSRV is considered a breaking change, as the last two versions did it too.
> Switch from `windows-targets` to `windows-link`
