Amanieu/parking_lot

benchmark/src/mutex.rs

When benchmarking a synchronization primitive, raw throughput is not the
only statistic that matters. For example, it is also important that
threads do not starve waiting to acquire a lock.
Improve the benchmark reporting so that it reports the throughput per
thread per second.  This makes it possible to compare benchmarks across
different numbers of threads.  Without this, benchmark runs with more
threads would naturally appear to have higher throughput.  Additionally,
include the median and standard deviation for the throughput per thread
per second so that starvation issues become more apparent.
Signed-off-by: Chirantan Ekbote <chirantan@google.com>

Improve benchmark reporting

---

.travis.yml
Cargo.toml
README.md
appveyor.yml
benchmark/Cargo.toml
core/Cargo.toml
core/src/lib.rs
core/src/parking_lot.rs
core/src/spinwait.rs
core/src/stable.rs
core/src/thread_parker/linux.rs
core/src/thread_parker/windows/keyed_event.rs
core/src/thread_parker/windows/mod.rs
core/src/thread_parker/windows/waitaddress.rs
core/src/word_lock.rs
src/condvar.rs
src/deadlock.rs
src/elision.rs
src/lib.rs
src/mutex.rs
src/once.rs
src/raw_mutex.rs
src/raw_remutex.rs
src/raw_rwlock.rs
src/remutex.rs
src/rwlock.rs
src/stable.rs

My stab to solve cc #18 using a wait graph. It requires more work but overall I think it's a good candidate for inclusion. Let me know your thoughts.
[x] feature flagged
[x] reasonably efficient
[nop] checking thread (automatic start?)
[x] reporting (how to?)
[ ] locking/unlocking in different threads break the algorithm

Implement deadlock detection

---

Cargo.toml
src/lib.rs
src/raw_rwlock.rs
src/rwlock.rs

Add upgradable guard to RwLock

---

Cargo.toml
core/Cargo.toml

[rand changelog](https://github.com/rust-lang-nursery/rand/blob/master/CHANGELOG.md)

Upgrade to rand 0.4

---

src/elision.rs

The assembly implementation of AtomicElisionExt does not build on x32 as the x86_64 assembly code does not build there.
While it should be generally possible to write an assembly implementation of AtomicElisionExt for x32 later - and, FWIW, for all the other architectures - this change will at least fix the build failure of ```parking_lot``` on x32.

Provide correct implementation of AtomicElisionExt for x32

---

core/src/parking_lot.rs
src/condvar.rs
src/mutex.rs
src/once.rs
src/remutex.rs
src/rwlock.rs

Fix was_last_thread value in the timeout callback of park()

---

core/src/parking_lot.rs

Every time the hash table is being resized the library calls `Instant::now()` `n` number of times, where `n` is the new size of the table. This PR reduces that to getting the current time a single time per resize operation.
Probably not noticeable on most platforms. But for example SGX has a really slow syscall to get the current time.
This was extracted from #119 in order to make that PR smaller, and more focused on what's actually needed for libstd. This commit in relevant for the library when used on its own.

Optimize grow_hashtable to call Instant::now() once

---

CHANGELOG.md

Fixes #142 
I added everything I saw in the git history that looked interesting enough to mention. My definition of "interesting enough" is:
* API breaking
* A bugfix
* Big improvement or new feature worth knowing about.
However, you have some "misc" PRs where you might have done something you feel worth mentioning that I missed?

Add changelog entries for the 0.8.0 release

---

lock_api/src/mutex.rs
lock_api/src/remutex.rs
lock_api/src/rwlock.rs
src/remutex.rs

Continuation of #140.
Picking misc issues from the review over at https://github.com/faern/parking_lot/pull/1 and fixing them.

Fix feedback from libstd, part 2

---

core/src/parking_lot.rs

The only time the special case of a null HashTable will happen is on the very first call. No need to optimize for it. The new behavior with `get_hashtable` should behave basically identical anyway.
An improvement is that it now only has to load `HASHTABLE` once before starting the work in the first loop.

Don't duplicate create_hashtable code in grow_hashtable

---

core/src/parking_lot.rs

Calling `grow_hashtable` can't do unsafe stuff unless `HASHTABLE` has been wrongfully manipulated. So there are no safety invariants to uphold as a caller. So it does not need to be `unsafe`. The little unsafe Rust used inside it has instead been contained and documented.
Moving the hardest to understand/read part, linked list handling, into a separate function for isolation and to make it easier to understand on its own.

Safe grow_hashtable

---

src/condvar.rs

As discussed during Impl days, I've gone and pretty much verbatim copied WebKit's `Condvar` tests here.

Add integration tests for Condvar

---

lock_api/src/mutex.rs
lock_api/src/remutex.rs
lock_api/src/rwlock.rs
src/raw_fair_mutex.rs
src/raw_mutex.rs
src/raw_rwlock.rs

Add RawMutex::is_locked()

---

core/src/thread_parker/windows/keyed_event.rs
core/src/thread_parker/windows/waitaddress.rs
src/condvar.rs
src/once.rs

The scope of the unsafe blocks can be appropriately reduced

Shrink unsafe blocks 

---

lock_api/src/mutex.rs

Fix `ArcMutexGuard` soundness

---

lock_api/src/mutex.rs
lock_api/src/remutex.rs
lock_api/src/rwlock.rs

This expands https://github.com/Amanieu/parking_lot/pull/369 to cover all guard types.
CC: @c410-f3r

Mark all guards as clippy::has_significant_drop

---

lock_api/src/rwlock.rs
tests/issue_392.rs

Fix `RwLockUpgradeableReadGuard::with_upgraded`

---

Cargo.toml

docs: Include some features when building for docs.rs.

---

core/src/thread_parker/unix.rs

Add the support of Apple VisionOS  [121419](https://github.com/rust-lang/rust/pull/121419)
Add target_os = "visionos"

Add Apple visionOS support

---

core/build.rs

**Description:**  
This pull request updates the variable name from `santizer_list` to `sanitizer_list` in `core/build.rs` for improved code clarity and consistency.

Refactor: Rename Variable in build.rs for Consistency

---

core/src/thread_parker/sgx.rs

Previously (now - start)  was always positive causing indefinite waiting. 
Correcting the above calculation in this commit

Correct timeout_nanos calculation in SGX ThreadParker.park_until

---

lock_api/src/mutex.rs
lock_api/src/remutex.rs
lock_api/src/rwlock.rs
src/mutex.rs

see https://github.com/Amanieu/parking_lot/issues/476

implement try_map variant function that can return an arbitrary value as err
